# -*- coding: utf-8 -*-
"""Generate the Rift Finder UI data files from v3: design_handoff_rift_finder/rift-data.js and
dig-data.js. Called by build_all_v3.py; never edit the output by hand.

The UI's data contract is kept: every field it already reads is present with the same name and
meaning. New fields are only ever added. Player-facing wording (reward codes expanded, ranges
written min–max) is produced here, in the build, with the verbatim line kept beside it.
"""
import hashlib, json, os, re
from collections import deque
from paths import DATA, UI
from reward_text import group_lines

HEADER = """// GENERATED FILE - DO NOT EDIT BY HAND.
// Generated by data/tools/build_ui_data.py (run data/tools/build_all_v3.py) on {generated}.
// Source: {sources}
// Regenerate instead of editing; data/tools/validate_all_v3.py checks this file against v3.
"""

GLOSSARY_6X = ("Reading payouts: \"6x\" means six months of your empire's current output of that "
               "resource, clamped to the min–max shown. The clamp is what you get at the extremes; "
               "for minor artifacts the three figures (e.g. 50 / 150 / 250) are the early, mid and "
               "late game values. A payout is never one fixed number.")

RIFT_GROUP = {"unique": "Unique", "precursor": "Precursor", "general": "General", "situation": "Situation"}

RIFT_CAT = {"relic": "Relics", "specimen": "Specimens (Grand Archive)", "cosmetic": "Other",
            "modifier": "Empire modifiers", "edict": "Edicts", "decision": "Planetary decisions",
            "deposit": "Rift deposits", "contact": "Diplomacy", "system": "Systems", "planet": "Planets",
            "situation": "Situations", "followup": "Unlocks", "recurring": "Empire modifiers",
            "undocumented": "Other", "leader": "Paragons & leaders", "trait": "Leader traits",
            "tech": "Technologies", "species": "Species & pops", "unit": "Ships & armies",
            "penalty": "Warnings"}

DIG_CAT = {"relic": "Relics", "specimen": "Specimens (Grand Archive)", "cosmetic": "Other",
           "modifier": "Empire & planet modifiers", "edict": "Empire & planet modifiers",
           "recurring": "Empire & planet modifiers", "decision": "Planetary decisions & features",
           "deposit": "Planets, deposits & systems", "planet": "Planets, deposits & systems",
           "system": "Planets, deposits & systems", "contact": "Vassals, diplomacy & federation",
           "situation": "Situations & event chains", "followup": "Situations & event chains",
           "undocumented": "Other", "leader": "Paragons & unique leaders",
           "trait": "Leader traits & leader effects", "tech": "Technologies",
           "species": "Species & pops", "unit": "Ships, armies & structures",
           "penalty": "Risks, costs & losses"}

# '"Visit the Black Curtain." (diff 0) → 3 [not Genocidal] (sets you on the 4-A branch)'
CHOICE = re.compile(r'^"(?P<t>.*?)"\s*(?:\(diff (?P<d>[^)]*)\))?\s*→\s*(?P<to>\S+)\s*(?P<n>.*)$')
ENDS = re.compile(r"^ends the rift\.?$", re.I)


def parse_choice(s):
    m = CHOICE.match(s)
    if not m:
        return None
    d = m.group("d")
    return {"text": m.group("t"), "diff": int(d) if d and d.lstrip("-").isdigit() else None,
            "to": m.group("to"), "note": m.group("n").strip()}


FAIL = re.compile(r"on failure →\s*(\S+)")


def ends(raw_choices, parsed):
    """A chapter ends the rift when it has no onward choice, says so, or a choice leads to END."""
    return (not any(parsed) or any(ENDS.match(x.strip()) for x in raw_choices)
            or any(p and p["to"] == "END" for p in parsed))


def s(v):
    return v if v is not None else ""


SHORT_MAX = 60
OVERRIDES = os.path.join(DATA, "overrides", "reward_names.json")
CHAPTER_REF = re.compile(r"\s+at chapter\s+[\w/-]+", re.I)   # internal wiki jargon; kept in the data, not shown


def reward_key(x):
    """Stable id for a reward: survives rebuilds and rid renumbering."""
    return f"{x['entity_uid']}#{x['chapter']}#{hashlib.sha1(x['raw'].encode()).hexdigest()[:10]}"


def load_name_overrides():
    return {k: v["short"] for k, v in json.load(open(OVERRIDES))["names"].items()} if os.path.exists(OVERRIDES) else {}
OPTION_PREFIX = re.compile(r"^\s*(?:choice(?:\s+of(?:\s+one)?)?|random|or)\b\s*(?:-\s*[^:]+)?\s*:?\s*", re.I)


def short_name(text, full=None):
    """(short, effect): a heading-length name and the effect text (audit U2).
    'Black Curtain + astral threads: +25% …' -> ('Black Curtain + astral threads', '+25% …').
    Without a colon, long names break at the first clause boundary, then at a word, and the effect
    is the full text. A name that is only an option marker ("Choice of one", "Random") falls back
    to the full text."""
    t = OPTION_PREFIX.sub("", text or "").strip()
    fullt = OPTION_PREFIX.sub("", full or "").strip() or t
    if not t:
        t = fullt
    t = t[:1].upper() + t[1:]
    fullt = fullt[:1].upper() + fullt[1:]
    tidy = lambda x: re.sub(r"(?:[\s,;:—-]+(?:or|and))+$", "", x.strip()).rstrip(" ,;:—-").strip()
    head, sep, rest = t.partition(":")
    if sep and 0 < len(head.strip()) <= SHORT_MAX:
        return tidy(head), rest.strip()
    if len(t) <= SHORT_MAX:
        short = tidy(t)
    else:
        short = None
        for cut in (" — ", " (", "; ", ", ", " - "):
            i = t.find(cut)
            if 0 < i <= SHORT_MAX:
                short = tidy(t[:i]); break
        if short is None:
            i = t.rfind(" ", 0, SHORT_MAX - 1)
            short = tidy(t[:i]) + "…"
    fh, fsep, frest = fullt.partition(":")
    if fsep and tidy(fh) == short:
        return short, frest.strip()
    effect = fullt if fullt.rstrip(" .") not in (short, short.rstrip("…")) else ""
    return short, effect


def _groups(lines, T):
    guaranteed, groups = group_lines(lines)
    return guaranteed, [{"kind": g["kind"],
                         "options": [dict(zip(("short", "shortDetail"), short_name(
                                          T.text(o["label"]) if o["label"] else T.text(o["text"]))),
                                      label=T.text(o["label"]) if o["label"] else T.text(o["text"]),
                                      payouts=[T.text(o["text"])], raw=lines[o["idx"]], line=o["idx"])
                                     for o in g["options"]]}
                        for g in groups]


# ---------------------------------------------------------------- rift paths

def _route(chapters, target_id):
    """Shortest chain of (chapter id, choice text) from the first chapter into target_id.
    A choice's "/ on failure → X" note is an edge too, so failure branches are reachable.
    Returns (steps, via_failure) or (None, False)."""
    by_id = {c["id"]: c for c in chapters}
    start = chapters[0]["id"]
    if target_id == start:
        return [], False
    prev, q = {start: None}, deque([start])
    while q:
        cur = q.popleft()
        for ch in by_id[cur]["choices"]:
            for nxt, fail in [(ch["to"], False)] + [(t, True) for t in FAIL.findall(ch["note"])]:
                if nxt in by_id and nxt not in prev:
                    prev[nxt] = (cur, ch["text"], fail)
                    q.append(nxt)
    if target_id not in prev:
        return None, False
    steps, node, last_fail = [], target_id, prev[target_id][2]
    while prev[node] is not None:
        cur, text, _ = prev[node]
        steps.append((cur, text)); node = cur
    return steps[::-1], last_fail


def _fmt(steps):
    return " -> ".join(f'{cid} "{txt}"' if txt else cid for cid, txt in steps)


def _curated_target(path, chapters):
    """The chapter a curated v2.1 path leads into (the last choice's destination)."""
    segs = [x.strip() for x in path.split("->")]
    m = re.match(r'^(\S+)\s+"(.*)"', segs[-1])
    if not m:
        return segs[-1].split()[0] if segs[-1] else None
    ch = next((c for c in chapters if c["id"] == m.group(1)), None)
    hit = ch and next((c for c in ch["choices"] if c["text"] == m.group(2)), None)
    return hit["to"] if hit else None


def _resolves(path, chapters):
    """Every segment starts with a real chapter id, and any quoted choice exists in it."""
    by_id = {c["id"]: c for c in chapters}
    for seg in (x.strip() for x in path.split("->")):
        m = re.match(r'^(\S+)(?:\s+"([^"]*)")?', seg)
        ch = by_id.get(m.group(1)) if m else None
        if not ch or (m.group(2) and m.group(2) not in [c["text"] for c in ch["choices"]]):
            return False
    return True


def rift_path(reward, chapters, finder):
    """Curated v2.1 path when it leads into this reward's chapter, else the computed route.
    Choice-sourced rewards end on the choice that grants them."""
    target = reward["chapter"]
    for f in finder:
        if f["entity"] != reward["entity"] or not f["path"]:
            continue
        same = f["reward"].lower() in (reward["raw"].lower(), reward["name"].lower()) or \
               f["reward"].lower() in reward["raw"].lower()
        if same and _curated_target(f["path"], chapters) == target and reward["source"] == "chapter" \
                and _resolves(f["path"], chapters):
            return f["path"], "curated"
    steps, via_failure = _route(chapters, target)
    if steps is None:
        # situation stages advance on progress, not on a choice: the path is the stage itself
        return target, "direct"
    if reward["source"] == "choice":
        ch = next(c for c in chapters if c["id"] == target)
        pick = next((c["text"] for c in ch["choices"]
                     if reward["raw"].lower()[:40] in (c["text"] + " " + c["note"]).lower()), None)
        steps = steps + [(target, pick)]
    return (_fmt(steps) if steps else target), ("failure" if via_failure else "computed")


# ---------------------------------------------------------------- relic detail for the UI

def relic_card(r):
    cost = ", ".join(f"{c['amount']:,} {c['resource'].title() if c['resource'].islower() else c['resource']}"
                     for c in r["triumph_cost"])
    return {"id": r["id"], "name": r["name"], "category": r["category"], "passive": r["passive"],
            "triumph": r["triumph"], "triumphCost": cost or None, "triumphCostItems": r["triumph_cost"],
            "cooldownDays": r["triumph_cooldown_days"], "activatable": r["activatable"],
            "source": r["source"], "dlc": r["dlc"], "stage": r["stage"]}


# ---------------------------------------------------------------- main

def main(rifts, arch, catalogue, T):
    r21 = json.load(open(f"{DATA}/astral_rifts.v2.1.json"))
    finder = [{"entity": f["entity"], "reward": f["reward"], "path": f["path"]} for f in r21["reward_finder"]]
    relic_by_id = {r["id"]: r for r in catalogue}
    names = load_name_overrides()
    used = set()

    def names_for(x):
        short, effect = short_name(T.text(x["name"]), x["text"])
        k = reward_key(x)
        if k in names:
            short = names[k]; used.add(k)
            effect = effect or x["text"]
        return CHAPTER_REF.sub("", short).strip(), CHAPTER_REF.sub("", effect).strip(), k

    # ---------------- rifts ----------------
    ui_rifts, chapters_by_rift = [], {}
    for e in rifts["entities"]:
        chs = []
        for c in sorted(e["chapters"], key=lambda x: x["index"]):
            parsed = [parse_choice(x) for x in c.get("choices", [])]
            guaranteed, groups = _groups(c["rewards"], T)
            chs.append({"id": c["id"], "title": s(c.get("title")),
                        "rewards": [T.text(x) for x in c["rewards"]],
                        "choices": [p for p in parsed if p],
                        "ends": ends(c.get("choices", []), parsed),
                        # added in the v3 generator
                        "index": c["index"], "raw": list(c["rewards"]),
                        "rawChoices": list(c.get("choices", [])),
                        "rewardChoices": groups, "guaranteed": guaranteed})
        chapters_by_rift[e["name"]] = chs
        ui_rifts.append({"name": e["name"], "group": RIFT_GROUP[e["group"]],
                         "req": T.text(s(e.get("requirements"))), "restrict": T.text(s(e.get("restrictions"))),
                         "notes": T.text(s(e.get("notes"))), "chapters": chs,
                         "uid": e["uid"], "kind": e["kind"], "groupKey": e["group"],
                         "groupLabel": e["group_label"], "dlc": s(e.get("dlc")),
                         "unlocks": e.get("unlocks", [])})

    ui_rewards, path_kinds = [], {"curated": 0, "computed": 0, "failure": 0, "direct": 0}
    for x in rifts["rewards"]:
        path, how = rift_path(x, chapters_by_rift[x["entity"]], finder)
        path_kinds[how] += 1
        short, effect, k = names_for(x)
        row = {"name": T.text(x["name"]), "rift": x["entity"], "path": path, "cat": RIFT_CAT[x["type"]],
               "short": short, "effect": effect, "key": k,
               "rid": x["rid"], "type": x["type"], "rewardGroup": x["group"],
               "rewardGroupLabel": x["group_label"], "chapter": x["chapter"], "source": x["source"],
               "polarity": x["polarity"], "conditional": x["conditional"], "gate": x["gate"],
               "text": x["text"], "raw": x["raw"], "pathSource": how}
        if x["type"] == "relic":
            row["relicId"] = x.get("relic_id")
            row["relic"] = relic_card(relic_by_id[x["relic_id"]]) if x.get("relic_id") else None
            if x.get("relic_link_exception"):
                row["relicNote"] = x["relic_link_exception"]
        ui_rewards.append(row)

    kinds = {e["kind"] for e in rifts["entities"]}
    rift_counts = {"rifts": sum(1 for e in rifts["entities"] if e["kind"] == "astral_rift"),
                   "situations": sum(1 for e in rifts["entities"] if e["kind"] == "astral_rift_situation"),
                   "entries": len(rifts["entities"]),
                   "chapters": rifts["coverage"]["chapters"], "rewards": len(rifts["rewards"]),
                   "payouts": len(rifts["payouts"])}
    rift_meta = {"generatedBy": "data/tools/build_ui_data.py", "generated": rifts["generated"],
                 "sources": [{"dataset": rifts["dataset"], "schema": rifts["schema"],
                              "version": rifts["version"], "generated": rifts["generated"],
                              "wiki_version": rifts["wiki_version"]},
                             {"dataset": "stellaris_relics", "file": "data/relics.v3.json"}],
                 "pathSources": path_kinds}
    rift_obj = {"rifts": ui_rifts, "rewards": ui_rewards, "meta": rift_meta, "counts": rift_counts,
                "relics": [relic_card(r) for r in catalogue if any(
                    x.get("relic_id") == r["id"] for x in rifts["rewards"])]}

    # ---------------- dig sites ----------------
    ui_sites = []
    for e in arch["entities"]:
        chs = []
        for c in sorted(e["chapters"], key=lambda x: x["index"]):
            guaranteed, groups = _groups(c["rewards"], T)
            chs.append({"id": c["id"], "rewards": [T.text(x) for x in c["rewards"]],
                        "index": c["index"], "raw": list(c["rewards"]),
                        "guaranteed": guaranteed, "choices": groups})
        ui_sites.append({"id": e["id"], "name": e["name"], "group": e["group"],
                         "groupLabel": e["group_label"], "dlc": s(e.get("dlc")),
                         "precursor": s(e.get("precursor")), "system": s(e.get("system")),
                         "req": T.text(s(e.get("requirements"))), "restrict": T.text(s(e.get("restrictions"))),
                         "notes": T.text(s(e.get("notes"))), "chapters": chs,
                         "uid": e["uid"], "unlocks": e.get("unlocks", [])})
    labels = {e["name"]: e["group_label"] for e in arch["entities"]}
    ids = {e["name"]: e["id"] for e in arch["entities"]}
    dig_rewards = []
    for x in arch["rewards"]:
        short, effect, k = names_for(x)
        row = {"cat": DIG_CAT[x["type"]], "name": T.text(x["name"]), "site": x["entity"],
               "short": short, "effect": effect, "key": k,
               "siteId": ids[x["entity"]], "chapter": x["chapter"], "groupLabel": labels[x["entity"]],
               "rid": x["rid"], "type": x["type"], "rewardGroup": x["group"],
               "rewardGroupLabel": x["group_label"], "source": x["source"], "polarity": x["polarity"],
               "conditional": x["conditional"], "gate": x["gate"], "text": x["text"], "raw": x["raw"]}
        if x["type"] == "relic":
            row["relicId"] = x.get("relic_id")
            row["relic"] = relic_card(relic_by_id[x["relic_id"]]) if x.get("relic_id") else None
        dig_rewards.append(row)
    dig_counts = {"sites": len(arch["entities"]), "phases": arch["coverage"]["chapters"],
                  "rewards": len(arch["rewards"]), "payouts": len(arch["payouts"]),
                  "choiceGroups": sum(len(c["choices"]) for s_ in ui_sites for c in s_["chapters"])}
    dig_meta = {"generatedBy": "data/tools/build_ui_data.py", "generated": arch["generated"],
                "sources": [{"dataset": arch["dataset"], "schema": arch["schema"],
                             "version": arch["version"], "generated": arch["generated"],
                             "wiki_version": arch["wiki_version"]}],
                "corrections": [{"entity": f["entity"], "op": f["op"], "revid": f["revid"], "why": f["why"]}
                                for f in arch.get("corrections", [])]}
    dig_obj = {"sites": ui_sites, "rewards": dig_rewards,
               "mechanics": [T.text(m) for m in arch["mechanics"]] + [GLOSSARY_6X],
               "groups": arch["groups"], "meta": dig_meta, "counts": dig_counts,
               "relics": [relic_card(r) for r in catalogue if any(
                   x.get("relic_id") == r["id"] for x in arch["rewards"])]}

    stale = sorted(set(names) - used)
    if stale:
        raise SystemExit(f"reward_names.json has {len(stale)} ids that match no reward (data changed?): {stale[:3]}")
    rift_meta["nameOverrides"] = sum(1 for x in ui_rewards if x["key"] in names)
    dig_meta["nameOverrides"] = sum(1 for x in dig_rewards if x["key"] in names)

    for fn, var, obj, src in (
            ("rift-data.js", "RIFT_DATA", rift_obj,
             f"data/astral_rifts.v3.json ({rifts['schema']}, v{rifts['version']}, generated "
             f"{rifts['generated']}, wiki {rifts['wiki_version']}) + data/relics.v3.json"),
            ("dig-data.js", "DIG_DATA", dig_obj,
             f"data/archaeological_sites.v3.json ({arch['schema']}, v{arch['version']}, generated "
             f"{arch['generated']}, wiki {arch['wiki_version']}) + data/relics.v3.json")):
        body = json.dumps(obj, ensure_ascii=False, separators=(",", ":"))
        with open(os.path.join(UI, fn), "w") as f:
            f.write(HEADER.format(generated=rifts["generated"], sources=src))
            f.write(f"window.{var}={body};\n")
        print(f"{fn:14} {len(body)//1024:4} KB")
    print(f"rift reward paths: {path_kinds}")
    print(f"UI counts: rifts {rift_counts}  sites {dig_counts}")
